using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// The rolled halves of an item — see Docs/EquipmentDesign.md "Principle 1b:
/// Fixed = identity, Rolled = texture".
///
/// * <see cref="affixPool"/> — every item draws one affix; its value rolls between min and max.
/// * <see cref="engravingPool"/> — Epic and Legendary items roll a SECOND Engraving from here
///   at drop time, beside their fixed signature.
///
/// Generated by Tools/EquipmentDesigner.html → Tools > Equipment > Import Design JSON.
/// </summary>
[CreateAssetMenu(menuName = "Data/EffectPoolDatabase")]
public class EffectPoolDatabase : ScriptableObject
{
    [Serializable]
    public class AffixEntry
    {
        public string name;
        [Tooltip("The stat modified, e.g. 'Max Health'")]
        public string stat;
        [Tooltip("'%' or 'flat'")]
        public string unit = "%";
        [Tooltip("Base roll range — scale up by rarity and act")]
        public float min, max;
        [Tooltip("Comma-separated slot names, or 'any'")]
        public string slots = "any";
        [Tooltip("Comma-separated theme names, or 'any'")]
        public string themes = "any";
        public float weight = 10f;
    }

    [Serializable]
    public class EngravingEntry
    {
        public string name;
        [TextArea(2, 3)] public string text;
        [Tooltip("HOOK / AMPLIFY / BREAK / REDEFINE — keep one tier below the host item")]
        public string verb = "HOOK";
        [Tooltip("Comma-separated pool tags an item's 'Roll pool' field can match")]
        public string pools;
        public string slots = "any";
        public float weight = 10f;
    }

    public List<AffixEntry> affixPool = new List<AffixEntry>();
    public List<EngravingEntry> engravingPool = new List<EngravingEntry>();

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static bool Matches(string csv, string value)
    {
        if (string.IsNullOrWhiteSpace(csv) || csv.Trim().Equals("any", StringComparison.OrdinalIgnoreCase))
            return true;
        foreach (var part in csv.Split(','))
            if (part.Trim().Equals(value, StringComparison.OrdinalIgnoreCase)) return true;
        return false;
    }

    /// <summary>Affixes legal for this slot + theme.</summary>
    public List<AffixEntry> AffixesFor(string slot, string theme)
    {
        var result = new List<AffixEntry>();
        foreach (var a in affixPool)
            if (Matches(a.slots, slot) && Matches(a.themes, theme)) result.Add(a);
        return result;
    }

    /// <summary>Secondary Engravings legal for this pool tag + slot.</summary>
    public List<EngravingEntry> EngravingsFor(string poolTag, string slot)
    {
        var result = new List<EngravingEntry>();
        foreach (var e in engravingPool)
            if (Matches(e.pools, poolTag) && Matches(e.slots, slot)) result.Add(e);
        return result;
    }

    /// <summary>Weighted pick from a list of entries.</summary>
    public static T WeightedPick<T>(List<T> list, Func<T, float> weight) where T : class
    {
        if (list == null || list.Count == 0) return null;
        float total = 0f;
        foreach (var i in list) total += Mathf.Max(0.01f, weight(i));
        float roll = UnityEngine.Random.Range(0f, total);
        foreach (var i in list)
        {
            roll -= Mathf.Max(0.01f, weight(i));
            if (roll <= 0f) return i;
        }
        return list[list.Count - 1];
    }
}
