using UnityEngine;

/// <summary>
/// Game-side item data, keyed by the same Id as HeroEditor's ItemParams.
/// HeroEditor keeps owning visuals + base stat Properties; this adds the design layer
/// (theme, rarity, affix, engraving, resonance) — see Docs/HeroEditorEquipment.md.
///
/// Generated by Tools/EquipmentDesigner.html → Tools > Equipment > Import Design JSON.
/// </summary>
[CreateAssetMenu(menuName = "Data/ItemDefinition")]
public class ItemDefinition : ScriptableObject
{
    [Header("Identity — id links to HeroEditor ItemParams.Id")]
    public string id;
    public string displayName;
    public string slot;
    public string spriteId;

    [Header("Design")]
    public string theme;
    [Tooltip("Common / Uncommon / Rare / Epic / Legendary")]
    public string rarity;

    [Header("Affix — the rolled stat modifier")]
    [Tooltip("The stat this affix modifies, e.g. 'Max Health'")]
    public string affix;
    [Tooltip("Rolled value range — same effect, different roll (free texture)")]
    public float affixMin;
    public float affixMax;
    [Tooltip("'%' or 'flat'")]
    public string affixUnit = "%";

    [Header("Signature Engraving — FIXED. The item's identity; what players hunt and attune toward.")]
    public string engravingName;
    [TextArea(2, 4)] public string engravingText;

    [Header("Rolled Engraving (Epic/Legendary only)")]
    [Tooltip("Epic & Legendary carry a SECOND Engraving rolled from a pool at drop time. " +
             "This names the pool to draw from — the effect itself is not authored per item.")]
    public string rolledEngravingPool;

    [Header("Resonance")]
    [Tooltip("The thematic counter, e.g. 'Absorb damage'")]
    public string resonanceRequirement;
    public string tierI;
    public string tierII;
    public string tierIII;

    [Header("Notes")]
    [TextArea(2, 5)] public string designerNotes;
}
